name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn --cwd client install 2>&1
    - name: Test jest
      run: yarn --cwd client jest -- --verbose=true /test/jest_unit.test /test/jest_component.test 2>&1
